apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.service.ports.grpc }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.ports.pgrpc }}
      targetPort: {{ .Values.service.ports.pgrpc }}
      protocol: TCP
      name: pgrpc
    - port: {{ .Values.service.ports.stripewh }}
      targetPort: {{ .Values.service.ports.stripewh }}
      protocol: TCP
      name: stripewh
  selector:
    app: {{ .Chart.Name }}
