replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/billing
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

service:
  ports:
    grpc: 5020
    pgrpc: 5120
    stripewh: 5028

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 500m
   memory: 512Mi
  requests:
   cpu: 500m
   memory: 512Mi

config:
  USERS_RPC_ADDR: "users.console.svc.cluster.local:5000"
  ACCOUNTS_RPC_ADDR: "accounts.console.svc.cluster.local:5001"
  EMITTER_RPC_ADDR: "emitter.console.svc.cluster.local:5003"

ingress:
  enabled: true
  host: bill.dev.videocoinapis.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
  secret: tls-cert-cloud-billing

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-billing"
  vault.hashicorp.com/agent-inject-secret-common: "videocoin/v1/networks/everest-dev/console/common"
  vault.hashicorp.com/agent-inject-secret-config: "videocoin/v1/networks/everest-dev/console/billing"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/common" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/billing" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
