replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/billing
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

service:
  ports:
    grpc: 5020
    pgrpc: 5120
    stripewh: 5028

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 500m
   memory: 512Mi
  requests:
   cpu: 50m
   memory: 32Mi

config:
  USERS_RPC_ADDR: "users.console.svc.cluster.local:5000"
  ACCOUNTS_RPC_ADDR: "accounts.console.svc.cluster.local:5001"
  EMITTER_RPC_ADDR: "emitter.console.svc.cluster.local:5003"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: console.dev.videocoin.network
      paths:
        - "/api/v1/stripe"
  tls:
    - secretName: tls-cert-console-billing
      hosts:
        - console.dev.videocoin.network

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-billing"
  vault.hashicorp.com/agent-inject-secret-common: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config"
  vault.hashicorp.com/agent-inject-secret-config: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/billing/config"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/billing/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
