replicasCount: 3
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/billing
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalRpcPort: 5020
  internalRpcPort: 5020
  externalPRpcPort: 5120
  internalPRpcPort: 5120
  externalWHPort: 5028
  internalWHPort: 5028

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

config: {}

secrets: {}
